const { Schema, model } = require("mongoose");
const storeofSchema = new Schema({
  _id: Schema.Types.ObjectId,
  Guild: String,
  guildID: String,
  guildname: String,
  prefix: String,
  oldPrefix: String,
  regChannel: String,
  logChannel: String,
  resultChannel: String,
  roleChannel: String,
  atRegChannel: String,
  idpassChannel: String,
  allowedAdminRoles: String,
  isPremeum: Boolean,
  autoEmbed: Array,
  communityRequs: [],
  welcomer: {
    channel: String,
    content: String,
    embed_title: String,
    embed_des: String,
    bgURL: String,
    avatar_border_color: String,
    welcome_color: String,
    username_color: String,
    message__text: String,
    message__color: String,
  },
  goodbay: {
    channel: String,
    content: String,
    embed_title: String,
    embed_des: String,
    bgURL: String,
    avatar_border_color: String,
    welcome_color: String,
    username_color: String,
    message__text: String,
    message__color: String,
  },
});

module.exports = model("guilds", storeofSchema, "StoreInformation");
